#!/usr/bin/env python
#coding:utf-8
# Author: zoraida
# Created: 01/04/2014
"""
Takes as input the output generated by lemmatizer
and outputs each document in one line
"""
import sys
import argparse
import codecs

INPUT_ENCODING = 'ISO-8859-1'
OUTPUT_ENCODING = 'UTF-8'

# From lemmatizer output file
LEMMA_SEPARATOR = u'¬'
INFOWORD_SEPARATOR = u'#'
WORD_SEPARATOR = u'  '

categories = ['NOMB', 'VERB', 'ADJ']


def parseLemma(lemma):
    return lemma.split(LEMMA_SEPARATOR)[0]


def generate(inputfile, outputfile):
    ofile = codecs.open(outputfile, encoding=OUTPUT_ENCODING, mode='w+')
    with codecs.open(inputfile, encoding=INPUT_ENCODING, mode='rb') as ifile:
        for text in ifile:
            textout = u''
            lastword = u''
            for wordinfo in text.strip().split(WORD_SEPARATOR):
                try:
                    word, lemma, category = wordinfo.split(INFOWORD_SEPARATOR)
                except:
                    print word, lemma, category
                if word != lastword:
                    lastword = word
                    if category in categories:
                        textout += u' ' + parseLemma(lemma)

            if textout != u'':
                ofile.write(textout.strip() + u'\n')


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("ifile", help="CSV input file")
    parser.add_argument("ofile", help="CSV output file")

    args = parser.parse_args()

    generate(args.ifile, args.ofile)

if __name__ == "__main__":
    main(sys.argv[1:])
