# Generated by CMake 2.8.11.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget det_id det_id_analytics gen_mod_idioma)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target det_id
add_library(det_id SHARED IMPORTED)

# Create imported target det_id_analytics
add_executable(det_id_analytics IMPORTED)

# Create imported target gen_mod_idioma
add_executable(gen_mod_idioma IMPORTED)

# Import target "det_id" for configuration ""
set_property(TARGET det_id APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(det_id PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/goyo/DetectorIdioma/src/libs/det_id/libdet_id.so"
  IMPORTED_SONAME_NOCONFIG "libdet_id.so"
  )

# Import target "det_id_analytics" for configuration ""
set_property(TARGET det_id_analytics APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(det_id_analytics PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/goyo/DetectorIdioma/src/apps/det_id_analytics/det_id_analytics"
  )

# Import target "gen_mod_idioma" for configuration ""
set_property(TARGET gen_mod_idioma APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gen_mod_idioma PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/goyo/DetectorIdioma/src/apps/gen_mod_idioma/gen_mod_idioma"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
